nateshmbhat/pyttsx3

pyttsx3/drivers/nsss.py
I ran the Usage example in both python2 and python3. Both worked fine after the fix and failed before the fix. 
```
import pyttsx3;
engine = pyttsx3.init();
engine.say("I will speak this text");
engine.runAndWait() ;
```
=> mwie's fix

requirements.txt, setup.py
Append `install_requires` list instead of overwriting so that universal" packages can be installed by specifying them within the install_requires list before customizing requirements based on the platform.
This should facilitate installation on Ubuntu and other linux flavors besides Darwin.
=> Update setup.py to allow hieraarchical install_requires

README.rst, setup.py
Use `extras_require` to specify platform specific requirements so the generated wheel is valid on all supported platforms (and not just the platform it was generated on).
Before (with the wheel available on PyPI):
```shell
> unzip -p dist/pyttsx3-2.7-py3-none-any.whl '*/METADATA' | grep Require
```
After:
```shell
> unzip -p dist/pyttsx3-2.7-py3-none-any.whl '*/METADATA' | grep Require
Requires-Dist: pyobjc (>=2.4); "darwin" in sys_platform
Requires-Dist: pypiwin32; "win32" in sys_platform
```
=> fix package requirements

README.md
The pypi link was to pypi, not to the pyttsx project page on pypi.
=> Fix pypi link

setup.py
- the platform specific dependencies are already handled by `extras_require`
- when the wheel is built on macos / windows the `install_requires` will contain extra values (it appears the one on pypi for the latest version was built on macos)
Resolves #88
Resolves #87 
Resolves #86
Resolves #83
Resolves #82
=> Fix wheel when built on macos / windows

setup.py
The latest wheel published on PyPI is not installable on Windows or Linux (presumably more releases are affected). This is because the current `setup.py` is querying the platform via code execution. While this will work with source dists, it breaks with wheels - the setup script is executed once when building the wheel, the metadata is written, the setup script is not touched again (in fact, it's not even included in the wheel). This means that e.g. the `pyttsx3-2.84-py3-none-any.whl` was built on MacOS and contains metadata for MacOS, so it is only installable on MacOS, because it pulls `pyobjc-security` on each install attempt.
The solution for this issue is to use the environment markers, specified in [PEP 508](https://www.python.org/dev/peps/pep-0508/#environment-markers). This makes …
=> use environment markers for platform specific dependencies

docs/drivers.rst
Just fixing a typo in the Drivers section
=> Fix typo in docs

pyttsx3/drivers/_espeak.py
This will enable support for espeak-ng, while keeping epseak functional.
=> Add support for eSpeak-ng

example/main.py, pyttsx3/drivers/_espeak.py, pyttsx3/drivers/espeak.py, pyttsx3/drivers/nsss.py, pyttsx3/drivers/sapi5.py
This PR adds pitch adjustment to espeak-ng, adds handling of pitch to other TTS engines to prevent errors, and cleans up a messy try/except block I added in a previous PR. It has worked through my test cases, (Tested on Windows, WSL, and Arch Linux).
This primarily addresses issue #164 
I also updated the example/main.py file to show the new feature.
=> Add pitch support to eSpeak-ng

pyttsx3/drivers/sapi5.py
The registry keys for some sapi5 voices have changed, along with their names, resulting in a failure to obtain an exact string match.  When this occurs, this revision defaults to the first voice in the list of drivers, or returns a ValueError if no voices are found.
=> Use any available voice if a match is not found with sapi5

pyttsx3/drivers/nsss.py
I traced the empty file / hanging behavior to `_busy` state management in the driver proxy. The underlying `NSSpeechSynthesizer` object behaves similarly for `say()` and `save_to_file()`, but `save_to_file()` was not updating the busy and completion states before starting synthesis the way that `say()` does. The state mismanagement caused the second call to `save_to_file()` to start an event loop that would never be terminated.
The intentions of the state management in the driver proxy are not perfectly clear to me, so this may not be a completely robust fix, but it does resolve the hanging behavior. Please note that you still must save `.aiff` or `.wav` files with the NSSS driver, not `.mp3`.
=> Resolves #142 for empty save_to_file() on darwin platform (NSSS driver)

pyttsx3/drivers/_espeak.py, pyttsx3/drivers/espeak.py
So I found eSpeak totally broken for me on all platforms. Yet to fully test on Linux. This now does word event timings as the normal code and speaks on MacOS and Windows. Apologies for all those docstring changes. Think that might be vscode being overly helpful.
=> fixes for word events, correct finding of espeak and playing of espeak

pyttsx3/driver.py, pyttsx3/drivers/nsss.py, pyttsx3/drivers/sapi5.py
If you run
```python
import pyttsx3
def onStart(name):
print('starting', name)
def onWord(name, location, length):
print('word', name, location, length)
def onEnd(name, completed):
print('finishing', name, completed)
engine = pyttsx3.init()
engine.connect('started-utterance', onStart)
engine.connect('started-word', onWord)
engine.connect('finished-utterance', onEnd)
engine.say('The quick brown fox jumped over the lazy dog.')
engine.runAndWait()
```
on SAPI it was still broken. Im not sure how - but I think one of the PRs cancelled out our changes. Nay mind this PR is better now as we now get
```bash
starting None
word The 0 3
word quick 4 5
word brown 10 5
word fox 16 3
word jumped 20 6
word over 27 4
word the 32 3
word lazy 36 4
word dog. 41 4
finishing None True
```
This works on SAPI …
=> SAPI and NSSS word events

pyttsx3/driver.py
Dict lookup is faster and more readable but the principal advantage is that Python 3.13 adds more `sys.platform`s like `android`, `ios`, and `emscripten` so the reliable expandability of drivers could come in handy.
* https://docs.python.org/3/library/sys.html#sys.platform
=> Use dict lookup of driver name by sys.platform

.github/workflows/python_publish.yml, pyttsx3/driver.py, pyttsx3/engine.py, tests/test_pyttsx3.py
Add `Engine.driver_name` and pytests for it.
Use Python [`sys.platform()`](https://docs.python.org/3/library/sys.html#sys.platform) to return all TTS Engines for the current OS.  The first TTS Engine in the tuple will be the default Engine for that OS.
```python
_engines_by_sys_platform = {
"darwin": ("nsss", "espeak"),  # NSSpeechSynthesizer (deprecated)
"win32": ("sapi5", "espeak"),
}
def engines_by_sys_platform() -> tuple[str]:
"""
Return the names of all TTS engines for the current operating system.
If sys.platform is not in _engines_by_sys_platform, return ("espeak",).
"""
return _engines_by_sys_platform.get(sys.platform, ("espeak",))
def default_engine_by_sys_platform() -> str:
"""
Return the name of the default TTS engine for the current operating system.
The first engine in the …
```
=> TTS engines by sys.platform

.pre-commit-config.yaml, example/repeatvoice.py, pyproject.toml, pyttsx3/drivers/_espeak.py, pyttsx3/drivers/espeak.py, tests/test_pyttsx3.py
% `pipx run ruff check --fix --unsafe-fixes`
* https://docs.astral.sh/ruff
=> `pipx run ruff check --fix --unsafe-fixes`

.github/workflows/python_publish.yml, pyttsx3/drivers/_espeak.py, tests/test_engines.py, tests/test_pyttsx3.py
% `brew info espeak-ng`
% `brew home espeak-ng`
% `brew install espeak-ng`
% `espeak-ng --version`
=> Enable eSpeak-NG on macOS

.github/workflows/python_publish.yml, tests/test_engines.py
```yaml
- name: Download and install eSpeak-NG
if: runner.os == 'Windows'
shell: pwsh
run: |
Invoke-WebRequest -Uri "https://github.com/espeak-ng/espeak-ng/releases/download/1.51/espeak-ng-X64.msi" -OutFile "espeak-ng.msi"
Start-Process msiexec.exe -ArgumentList '/i espeak-ng.msi /quiet /norestart' -Wait
$env:Path += ";$env:ProgramFiles\eSpeak NG"
espeak-ng --version
```
=> Enable eSpeak-NG on Windows

.github/workflows/python_publish.yml
https://pypi.org/project/pytest-timeout provides a good explanation of why this dependency should only be used sparingly.
We no longer need it so let's remove it.
=> Remove pytest-timeout

.github/workflows/python_publish.yml, pyttsx3/drivers/espeak.py, tests/test_engines.py, tests/test_pyttsx3.py
```
tests/test_engines.py::test_espeak_voices[espeak] ['espeak']
espeak
espeak has len(voices) = 131 voices.
(Caribbean ; Great Britain ; Scotland ; Lancaster ; West Midlands ; Received Pronunciation ; America
; America, New York City) PASSED
```
=> Add `test_espeak_voices(driver_name="espeak")`

pyttsx3/drivers/_espeak.py
```diff
def Synth(
text,
position=0,
position_type=POS_CHARACTER,
end_position=0,
flags=0,
user_data=None,
):
+   if isinstance(text, str):
+       text = text.encode("utf-8")
return cSynth(
text,
```
Before:
% `python pyttsx3/drivers/_espeak.py`
```
ctypes.ArgumentError: argument 1: TypeError: 'str' object cannot be interpreted as ctypes.c_char_p
```
After: eSpeak-NG pronounces the message.
=> Fix `python pyttsx3/drivers/_espeak.py`

example/repeatvoice.py, pyproject.toml, pyttsx3/drivers/nsss.py, tests/test_pyttsx3.py
Fix our tests to deal with the `.aiff` vs. `.wav` issue discussed at https://github.com/nateshmbhat/pyttsx3/issues/361#issuecomment-2461907598
Also fixes a crash bug in `example/repeatvoice.py`.
=> Apple NSSpeechSynthesizer (`nsss`) writes .aiff, not .wav files

.pre-commit-config.yaml, README.md
|                         | Linux | macOS | Windows |
|-------------------------|:-----:|:-----:|:-------:|
| [AVSpeech][]            |       |   ✅︎  |         |
| [eSpeak][]              |   ✅︎  |   ✅︎  |    ✅︎   |
| [NSSpeechSynthesizer][] |       |   ✅︎  |         |
| [SAPI5][]               |       |       |    ✅︎   |
> [!NOTE]  
> * AVSpeech support is still experimental.
> * NSSpeechSynthesizer is deprecated by Apple.
[AVSpeech]: https://developer.apple.com/documentation/avfoundation/speech_synthesis
[eSpeak]: https://github.com/espeak-ng/espeak-ng?tab=readme-ov-file#readme
[NSSpeechSynthesizer]: https://developer.apple.com/documentation/appkit/nsspeechsynthesizer
[SAPI5]: https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ms723627(v=vs.85)
---
In future pull …
=> README.md: Text-To-Speech Engines by Operating System

tests/test_pyttsx3.py
This test needs to pass on macOS.
=> Remove xfail from test_saving_to_file on macOS

pyttsx3/drivers/sapi5.py
nb; using locale to get correct lang codes that are understandable
This matches eSpeak too 
You should now get data like
```
<Voice id=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_DAVID_11.0
name=Microsoft David Desktop - English (United States)
languages=['en-US']
gender=Male
age=Adult>
<Voice id=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_ZIRA_11.0
name=Microsoft Zira Desktop - English (United States)
languages=['en-US']
gender=Female
age=Adult>
<Voice id=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_ES-ES_HELENA_11.0
name=Microsoft Helena Desktop - Spanish (Spain)
languages=['es-ES']
gender=Female
age=Adult>
<Voice id=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_FR-FR_HORTENSE_11.0 …
```
=> SAPI - Language codes and other fields to not be Empty (fix for #384)

.pre-commit-config.yaml, tests/test_engines.py
% `pre-commit autoupdate && pre-commit run --all-files`
* https://github.com/astral-sh/ruff/releases
* https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md
=> ruff-pre-commit updating v0.7.4 -> v0.8.6

example/main.py, example/repeatvoice.py
https://peps.python.org/pep-0723 enables Python files to have a header like:
```python
```
to Python scripts, which enables:
`pipx run examples/main.py` or
`uv run --script examples/main.py`.
When this command is run, `pipx` or `uv` will import the `dependencies` from PyPI, put them in an isolated `venv`, and then run the script in that `venv`.
https://thisdavej.com/share-python-scripts-like-a-pro-uv-and-pep-723-for-easy-deployment
=> Add PEP 723 headers to the examples

.pre-commit-config.yaml, tests/test_engines.py, tests/test_pyttsx3.py
% `pre-commit autoupdate`
```
[https://github.com/pre-commit/pre-commit-hooks] updating v5.0.0 -> v6.0.0
[https://github.com/MarcoGorelli/auto-walrus] already up to date!
[https://github.com/codespell-project/codespell] already up to date!
[https://github.com/astral-sh/ruff-pre-commit] updating v0.12.1 -> v0.12.10
```
% `pre-commit run --all-files`
=> On macOS v15.x, nsss has 177 voices
